name: Kim Haskell Cinematography
favicon: null
layout_spectrum: 0.14135
typography_spectrum: 0.72013
title: Kim Haskell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efe8d5'
    - '#3c3c39'
    - '#b19875'
    - '#0b0d0a'
    - '#707b8c'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
